define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for charts generated by Appery.io
         * @module charts
         */
        APP.controller('charts', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                /*var requestData = {};


Apperyio.get("ChartsData_data_list_service")(requestData).then(

    function(success) {
        (function mapping8035(success, $scope) {
            var labels_scope = $scope.labels;
            var series_scope = $scope.series;
            var data_scope = $scope.data;
            labels_scope = success.data[0].labels;
            series_scope = success.data[0].series;
            data_scope = success.data[0].data;
            $scope.labels = labels_scope;
            $scope.series = series_scope;
            $scope.data = data_scope;
            $scope.chartData = {
                labels: $scope.labels,
                series: $scope.series,
                data: $scope.data
            };

        })(success, $scope);

    },
    function(error) {


    },
    function(notify) {

    });*/
                $scope.chartData = {
                    labels: ["January", "February", "March", "April", "May", "June", "July"],
                    series: ['Foo', 'Baz', 'Bar'],
                    data: [
                        [65, 59, 80, 81, 56, 55, 40],
                        [28, 48, 40, 19, 86, 27, 90],
                        [42, 17, 28, 73, 50, 12, 68]
                    ]
                };
                $scope.type = 'Line';
            };
            /**
             * @function switchChartType
             * @param newType
             */
            $scope.switchChartType = function(newType) {
                $scope.type = newType;
            };
        }
    });