define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for SelectUser generated by Appery.io
         * @module SelectUser
         */
        APP.controller('SelectUserController', ['$scope', 'Apperyio', SelectUserController]);

        function SelectUserController($scope, Apperyio) {
            // user controller variables
            $scope.seluserlist = Apperyio.EntityAPI('SelUsers');
            $scope.id = Apperyio.EntityAPI('String');
            $scope.searchVal = Apperyio.EntityAPI('SearchVal');
            // user controller functions
            /**
             * @function init
             */
            $scope.init = function() {
                $scope.loadSelUsers();
            };
            /**
             * @function loadSelUsers
             */
            $scope.loadSelUsers = function() {
                var requestData = {};
                /*|button_mapping|onbeforesend|1C7A639D-CEBB-02B4-9468-F3E5282F4C1F||9117|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("getAllRegisteredUsers")(requestData).then( /*|service_bookmark|bookmark|1C7A639D-CEBB-02B4-9468-F3E5282F4C1F||4421|*/
                    function(success) { // success callback
                        var seluserlist_scope = $scope.seluserlist;
                        seluserlist_scope = success.data.users;
                        $scope.seluserlist = seluserlist_scope;
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function checked
             * @param id
             */
            $scope.checked = function(id) {
                angular.forEach($scope.seluserlist, function(value, key) {
                    if (value.id == id) {
                        value.checked = !value.checked;
                    }
                });
            };
            /**
             * @function send
             */
            $scope.send = function() {
                angular.forEach($scope.seluserlist, function(value, key) {
                    if (value.checked === true) {
                        var requestData = {};
                        requestData = (function mapping1840($scope) {
                            var requestData = {};
                            requestData.params = {};
                            requestData.params.to = value.email;
                            requestData.params.subject = "Weekly Report";
                            requestData.params.text = "<div><img src='https://www.theatreprofile.com/images/logo_522X203.png' class='img-default' alt='Image error' style='width: 100%;'></div>";
                            requestData.params.text += "<div><p style='padding-left: 5px;'>Hi, " + value.username + "</p>";
                            requestData.params.text += "<p style='padding-left: 5px;'>This is your introduction. You can tell the user a little about what is going on with TheatreProfile here, why they're getting this email, etc. This email is responsive, meaning it will look good on mobile or the web." + "</p>";
                            requestData.params.text += "<p style='margin-left:30px;margin-right: 30px;'><b>Tip #1:</b> Track your comps from week-to-week or show-to-show to make sure you aren't giving away too many tickets. If your attendance and comps are both growing, you may be giving away too many seats!</p></div>";
                            requestData.params.text += "<div style='text-align:center'><p style='color: #cbc8c8;'>My Dashboard</p>";
                            requestData.params.text += "<h1>Weekly Report</h1></div>";
                            requestData.params.text += "<img src='https://image-charts.com/chart?chs=700x300&amp;chxt=x,y&amp;chl=||&amp;chd=t:60,40,20&amp;cht=pa&amp;chdl=Legally Blonde|Young Frankenstein|Steel Magnolias&amp;chf=ps0-0,lg,45,ffeb3b,0.2,f443367C,1|ps0-1,lg,45,8bc34a,0.2,0096887C,1|ps0-2,lg,45,EA469E,0.2,03A9F47C,1&amp;chan'>";
                            requestData.params.text += "<br><br>"
                            requestData.params.text += "<img src='https://image-charts.com/chart?cht=bvg&amp;chd=t:25,80&amp;chs=500x300&amp;chxt=x,y&amp;chxl=0:%7CLast Week%7CThis Week&amp;chdl=Ticket Sales%20(in%20thousands%29&amp;chf=b0,lg,90,cc0000,1,cc0000,0.2&amp;chxs=1N**&amp;chma=0,0,10,10&amp;'>";
                            return requestData;
                        })($scope);
                        Apperyio.get("MailgunEmail_Mailgun_service")(requestData).then(
                            function(success) { // success callback
                                console.log("success");
                                $scope.modal.hide();
                            },
                            function(error) {
                                alert(error);
                            }
                        );
                    }
                });
            };
            /**
             * @function Search
             * @param event
             */
            $scope.Search = function(event) {
                if (event.keyCode == 13) {
                    console.log($scope.searchVal.val);
                }
            };
        }
    });