define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for mailgun generated by Appery.io
         * @module mailgun
         */
        APP.controller('mailgun', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.email = Apperyio.EntityAPI('Email_2');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                // On load screen logic
                $scope.email.from = "Excited User <user@enter-your-domain.mailgun.org>";
            };
            /**
             * @function sendEmail
             */
            $scope.sendEmail = function() {
                var requestData = {};
                requestData = (function mapping1383($scope) {
                    var requestData = {};
                    requestData.params = Apperyio.EntityAPI('MailgunEmail_Mailgun_service.request.query', undefined, true);
                    var email_scope = $scope.email;
                    requestData.params.to = email_scope.to;
                    requestData.params.subject = email_scope.subject;
                    requestData.params.text = email_scope.body;
                    return requestData;
                    /*|button_mapping|onbeforesend|95970489-C69F-4A16-8FA6-D7AB134344FE||1383|*/
                })($scope);
                // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
                Apperyio.get("MailgunEmail_Mailgun_service")(requestData).then( /*|service_bookmark|bookmark|95970489-C69F-4A16-8FA6-D7AB134344FE||1927|*/
                    function(success) { // success callback
                        /*|button_mapping|onsuccess|95970489-C69F-4A16-8FA6-D7AB134344FE||9730|*/
                        $scope.showAlert("Email sent. Thanks for using Appery.io + Mailgun.");
                    },
                    function(error) { // callback to handle request error
                        $scope.showAlert("Error sending email. Please check API settings.");
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function showAlert
             * @param msg
             */
            $scope.showAlert = function(msg) {
                var $ionicPopup = Apperyio.get("$ionicPopup");
                var alertPopup = $ionicPopup.alert({
                    title: 'Information',
                    template: msg
                });
                alertPopup.then(function(res) {
                    // you can do something here
                });
            };
        }
    });