define(['require'], function(require) {
    /**
     * Routing configuration generated by Appery.io
     */
    /**
     * Default route
     * @type {{redirectTo: string}}
     */
    var default_route = {
        redirectTo: '/DashboardOrganization.html'
    };
    /**
     * Routing configuration object
     * @property {object} default                               - Default routing configuration
     * @property {string} default.redirectTo                    - Default routing URL
     * @property {object} when                                  - Routing configuration for different URLs
     * @property {object} when./                                - Routing configuration for "/" URL
     * @property {string} when./.redirectTo                     - Redirect to default routing URL
     * @property {object} when["/DashboardOrganization.html"]    - Routing configuration for /DashboardOrganization.html URL
     * @property {string} when["/DashboardOrganization.html"].c  - Controller for /DashboardOrganization.html URL
     * @property {string} when["/DashboardOrganization.html"].t  - Template for /DashboardOrganization.html URL
     * @property {string[]} when["/DashboardOrganization.html"].d  - Dependencies for /DashboardOrganization.html URL
     * @property {object} when["/Screen1.html"]    - Routing configuration for /Screen1.html URL
     * @property {string} when["/Screen1.html"].c  - Controller for /Screen1.html URL
     * @property {string} when["/Screen1.html"].t  - Template for /Screen1.html URL
     * @property {string[]} when["/Screen1.html"].d  - Dependencies for /Screen1.html URL
     * @property {object} when["/Screen1.html"]    - Routing configuration for /Screen1.html URL
     * @property {string} when["/Screen1.html"].c  - Controller for /Screen1.html URL
     * @property {string} when["/Screen1.html"].t  - Template for /Screen1.html URL
     * @property {string[]} when["/Screen1.html"].d  - Dependencies for /Screen1.html URL
     * @property {object} when["/Screen1.html"]    - Routing configuration for /Screen1.html URL
     * @property {string} when["/Screen1.html"].c  - Controller for /Screen1.html URL
     * @property {string} when["/Screen1.html"].t  - Template for /Screen1.html URL
     * @property {string[]} when["/Screen1.html"].d  - Dependencies for /Screen1.html URL
     * @property {object} when["/charts.html"]    - Routing configuration for /charts.html URL
     * @property {string} when["/charts.html"].c  - Controller for /charts.html URL
     * @property {string} when["/charts.html"].t  - Template for /charts.html URL
     * @property {string[]} when["/charts.html"].d  - Dependencies for /charts.html URL
     * @property {object} when["/Screen1.html"]    - Routing configuration for /Screen1.html URL
     * @property {string} when["/Screen1.html"].c  - Controller for /Screen1.html URL
     * @property {string} when["/Screen1.html"].t  - Template for /Screen1.html URL
     * @property {string[]} when["/Screen1.html"].d  - Dependencies for /Screen1.html URL

     * @property {object} otherwise                             - Routing configuration for another URL
     * @property {object} otherwise.redirectTo                  - Redirect to default routing URL
     * @property {object} route_names                           - Route aliases
     * @property {string} route_names.["DashboardOrganization"]  - "DashboardOrganization" is an alias for "/DashboardOrganization.html" routing
     * @property {string} route_names.["Screen1_Mailgun_Email_API"]  - "Screen1_Mailgun_Email_API" is an alias for "/Screen1.html" routing
     * @property {string} route_names.["Screen1_Mailgun_Email_API_Email_with_Mailgun"]  - "Screen1_Mailgun_Email_API_Email_with_Mailgun" is an alias for "/Screen1.html" routing
     * @property {string} route_names.["Screen1_Mailgun_Email_API_Email_with_Mailgun_2"]  - "Screen1_Mailgun_Email_API_Email_with_Mailgun_2" is an alias for "/Screen1.html" routing
     * @property {string} route_names.["Charts"]  - "Charts" is an alias for "/charts.html" routing
     * @property {string} route_names.["Screen1_Mailgun_Email_API_Email_with_Mailgun_3"]  - "Screen1_Mailgun_Email_API_Email_with_Mailgun_3" is an alias for "/Screen1.html" routing

     */
    return {
        default: default_route,
        when: {
            '/': default_route,
            '/DashboardOrganization.html': {
                c: '$DashboardOrganization/DashboardOrganizationController',
                t: '$DashboardOrganization/DashboardOrganizationTemplate.html',
                d: []
            },
            '/charts.html': {
                c: '$charts/chartsController',
                t: '$charts/chartsTemplate.html',
                d: []
            },
            '/Screen1.html': {
                c: '$mailgun/mailgunController',
                t: '$mailgun/mailgunTemplate.html',
                d: []
            }
        },
        otherwise: default_route,
        route_names: {
            'DashboardOrganization': '/DashboardOrganization.html',
            'Screen1_Mailgun_Email_API': '/Screen1.html',
            'Screen1_Mailgun_Email_API_Email_with_Mailgun': '/Screen1.html',
            'Screen1_Mailgun_Email_API_Email_with_Mailgun_2': '/Screen1.html',
            'Charts': '/charts.html',
            'Screen1_Mailgun_Email_API_Email_with_Mailgun_3': '/Screen1.html'
        }
    };
});